name: Build g2o for aarch64 with musl

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: aarch64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up dockcross
      run: |
        docker run --rm dockcross/linux-arm64-musl > ./dockcross-linux-arm64-musl
        chmod +x ./dockcross-linux-arm64-musl

    - name: Install dependencies
      run: |
        ./dockcross-linux-arm64-musl bash -c 'apt-get update && apt-get install -y cmake g++ git'

    - name: Build g2o for aarch64 with musl
      run: |
        ./dockcross-linux-arm64-musl bash -c 'cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=/usr/aarch64-linux-musl/toolchain.cmake && cmake --build build'

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: g2o-aarch64-musl-build
        path: build/
