name: Build g2o for aarch64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: aarch64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build g2o for aarch64
      run: |
        docker run --rm dockcross/linux-arm64 > ./dockcross-linux-arm64
        chmod +x ./dockcross-linux-arm64
        ./dockcross-linux-arm64 bash -c 'cmake -S . -B build && cmake --build build'

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: g2o-aarch64-build
        path: build/

