name: Harmony OS Build

on:
  push:
    branches:
      - master
      - pymem
  pull_request:

  release:

jobs:
  build:
    name: Harmony OS Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Harmony OS aarch64 musl",
            os: ubuntu-latest,
            build_type: "Debug",
            generators: "Ninja"
          }

    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 25

      - name: Print env
        run: |
          echo github.ref: ${{github.ref}}
          echo github.event.action: ${{github.event.action}}
          echo github.event_name: ${{github.event_name}}
          echo runner.os: ${{runner.os}}
          env

      - name: Install dependencies for Harmony OS
        run: |
          sudo apt update
          sudo apt install cmake gcc-aarch64-linux-gnu musl-tools

      - name: Configure CMake for Harmony OS
        run: |
          echo "number of cores: $(nproc)"
          cmake --version
          cmake -B ${{github.workspace}}/build -G "${{matrix.config.generators}}" -DBUILD_UNITTESTS=ON -DG2O_BUILD_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=aarch64 -DCMAKE_C_COMPILER_TARGET=aarch64-linux-musl -DCMAKE_CXX_COMPILER_TARGET=aarch64-linux-musl

      - name: Build Introspection
        run: |
          echo "Number of processors: $Env:NUMBER_OF_PROCESSORS"
          echo "g2o config.h"
          cat ${{github.workspace}}/build/g2o/config.h

      - name: Build
        run: cmake --build ${{github.workspace}}/build -j $(nproc) --config ${{matrix.config.build_type}}

      - name: Test
        run: |
          cd ${{github.workspace}}/build
          $Env:PATH += ";${{github.workspace}}\build\bin"
          $Env:PATH += ";${{github.workspace}}\build\lib"
          ctest -C ${{matrix.config.build_type}} --extra-verbose --output-on-failure
